/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

public class ThongTinLopHoc extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinLopHoc
     */
    public ThongTinLopHoc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        txtTenLop = new javax.swing.JTextField();
        txtGiaoVienCN = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("THÔNG TIN LỚP HỌC");

        jLabel2.setText("Mã số lớp: ");

        jLabel3.setText("Tên lớp: ");

        jLabel4.setText("Giáo viên CN: ");

        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSave.setText("Lưu");

        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("Xoá");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnShow.setText("Hiển Thị");
        btnShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowActionPerformed(evt);
            }
        });

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Lớp Học", "Tên Lớp", "Giáo viên CN"
            }
        ));
        tbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaoVienCN))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMa)
                                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18)
                                .addComponent(btnDelete))
                            .addComponent(btnShow))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd)
                            .addComponent(btnSave))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEdit)
                        .addComponent(btnDelete)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtGiaoVienCN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowActionPerformed
        try {
            Connection kn = Ketnoi.Ketnoi.KetnoiSQL();
            String query = "SELECT * FROM thongtinlophoc";
            Statement stm = kn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
            dtm.setRowCount(0);
            /// kiem tra cac hang chay tu 0 -> n 
            while (rs.next()) {
                Object objList[] = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),};
                dtm.addRow(objList);
            }
            tbl.setModel(dtm);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnShowActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            Connection kn = Ketnoi.Ketnoi.KetnoiSQL();
            String maLop = txtMa.getText();
            String tenLop = txtTenLop.getText();
            String gvCN = txtGiaoVienCN.getText();
            String query = "INSERT INTO thongtinlophoc VALUES ('" + maLop + "', '" + tenLop + "', N'" + gvCN + "')";
            Statement stm = kn.createStatement();
            stm.executeUpdate(query);

            DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
            dtm.setRowCount(0);
            String sql1 = "SELECT * FROM thongtinlophoc";
            ResultSet rs = stm.executeQuery(sql1);
            while (rs.next()) {
                Object objList[] = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3)
                };
                // add cac ban ghi vao mảng objectlist
                dtm.addRow(objList);
            }
            tbl.setModel(dtm);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void tblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMouseClicked
        int row = tbl.getSelectedRow();
        String ma = tbl.getValueAt(row, 0).toString();
        String tenLop = tbl.getValueAt(row, 1).toString();
        String gvCN = tbl.getValueAt(row, 2).toString();

        txtMa.setText(ma);
        txtTenLop.setText(tenLop);
        txtGiaoVienCN.setText(gvCN);
    }//GEN-LAST:event_tblMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String maLopEdit = txtMa.getText();
        String tenLop = txtTenLop.getText();
        String gvCN = txtGiaoVienCN.getText();
        try {
            Connection ketnoi = Ketnoi.Ketnoi.KetnoiSQL();
            String querry2 = "UPDATE thongtinlophoc SET tenLop = '" + tenLop + "', giaovienCN = N'" + gvCN + "' WHERE msLop = '" + maLopEdit + "'";
            Statement stm = ketnoi.createStatement();
            stm.executeUpdate(querry2);

            String sql1 = "SELECT * FROM thongtinlophoc";
            ResultSet rs = stm.executeQuery(sql1);
            DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
            dtm.setRowCount(0);
            while (rs.next()) {
                Object objList[] = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),};

                dtm.addRow(objList);
                tbl.setModel(dtm);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed
    private void hienThiDuLieu() {
        try {
            Connection kn = Ketnoi.Ketnoi.KetnoiSQL();
            String query = "SELECT * FROM thongtinlophoc";
            Statement stm = kn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            DefaultTableModel dtm = (DefaultTableModel) tbl.getModel();
            dtm.setRowCount(0);
            // kiểm tra các hàng chạy từ 0 -> n
            while (rs.next()) {
                Object objList[] = {
                    rs.getInt(1),
                    rs.getString(2),
                    rs.getString(3),};
                dtm.addRow(objList);
            }
            tbl.setModel(dtm);
            stm.close();
            rs.close();
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    private void ClearTextField(){
        txtMa.setText("");
        txtTenLop.setText("");
        txtGiaoVienCN.setText("");
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Connection c = null;
        try {
            c = Ketnoi.Ketnoi.KetnoiSQL();
            // Lấy chỉ số của hàng được chọn từ bảng
            int selectedRow = tbl.getSelectedRow();

            if (selectedRow != -1) { 
                String ma = tbl.getValueAt(selectedRow, 0).toString(); 
                // Tạo truy vấn xóa dựa trên mã máy
                String del = "DELETE FROM thongtinlophoc WHERE msLop = '" + ma + "'";
                Statement stm = c.createStatement();
                int result = stm.executeUpdate(del);
                if (result > 0) {
                    hienThiDuLieu();
                    ClearTextField();
                } else {
                    // Xóa không thành công, xử lý tùy theo yêu cầu
                }

                // Đóng Statement
                stm.close();
            } else {
                // Hiển thị thông báo cho người dùng nếu không có hàng nào được chọn
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } finally {
            try {
                // Đóng kết nối sau khi sử dụng xong
                if (c != null) {
                    c.close();
                }
            } catch (SQLException ex) {
                java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinLopHoc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinLopHoc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtGiaoVienCN;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
